Add `repo-access` script
- script is partially working
- add `enforce_flag` to create-repo

see #14

diff --git a/lib/github.in b/lib/github.in
--- a/lib/github.in
+++ b/lib/github.in
@@ -12,34 +12,35 @@ DEFINE_string username "$(git config user.name)" 'GitHub user for authentication
 DEFINE_string token "$(git config $TOKEN_VAR)" 'GitHub token for authentication' 't'
 DEFINE_boolean version false 'Version of the tools package' 'v'
 
-# exit if we have displayed help text
-[ "${FLAGS_help}" = "${FLAGS_TRUE}" ] && exit 0
+enforce_flags() {
+    # exit if we have displayed help text
+    [ "${FLAGS_help}" = "${FLAGS_TRUE}" ] && exit 0
 
-# exist after showing the version
-[ "${FLAGS_version}" = "${FLAGS_TRUE}" ] && 
-{
-    echo "PACKAGE_VERSION"
-    exit 0
+    # exist after showing the version
+    [ "${FLAGS_version}" = "${FLAGS_TRUE}" ] && 
+    {
+        echo "PACKAGE_VERSION"
+        exit 0
+    }
+
+    # ensure jq is installed
+    JQ=$(which jq) || 
+    {
+        log ERROR "Could not find jq. Is it installed?"
+        exit 1
+    }
+
+    # ensure we have github user
+    [ "$FLAGS_username" ] || 
+    {
+        log ERROR "Could not find username.\nRun 'git config --global github.user <username>'"
+        exit 1
+    }
+
+    # ensure we have a token
+    [ "$FLAGS_token" ] || 
+    {
+        log ERROR "Could not find token.\nRun 'git config --global $TOKEN_VAR <token>'"
+        exit 1
+    }
 }
-
-# ensure jq is installed
-JQ=$(which jq) || 
-{
-    log ERROR "Could not find jq. Is it installed?"
-    exit 1
-}
-
-# ensure we have github user
-[ "$FLAGS_username" ] || 
-{
-    log ERROR "Could not find username.\nRun 'git config --global github.user <username>'"
-    exit 1
-}
-
-# ensure we have a token
-[ "$FLAGS_token" ] || 
-{
-    log ERROR "Could not find token.\nRun 'git config --global $TOKEN_VAR <token>'"
-    exit 1
-}
-
